# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [1]:
import numpy as np

sqmeter = [100, 95, 55, 45, 65, 75, 125, 145, 165, 185]
rooms = [3, 2, 2, 1, 2, 2, 2, 3, 4, 5]
price = [400, 350, 250, 200, 225, 275, 300, 250, 500, 700]


sq_array = np.array(sqmeter)
rooms_array = np.array(rooms)
price_array = np.array(price)

houses_array = np.array([sq_array, rooms_array, price_array])

print(houses_array)


[[100  95  55  45  65  75 125 145 165 185]
 [  3   2   2   1   2   2   2   3   4   5]
 [400 350 250 200 225 275 300 250 500 700]]


2. Transpose the array you have created, so that every line can represent features of one house.

In [39]:
array2 = houses_array.transpose()
print(array2)

[[100   3 400]
 [ 95   2 350]
 [ 55   2 250]
 [ 45   1 200]
 [ 65   2 225]
 [ 75   2 275]
 [125   2 300]
 [145   3 250]
 [165   4 500]
 [185   5 700]]


3. Display the shape of the array and explain what it means.

In [44]:
print(array2.shape)
print("It means it has 10 rows and 3 columns")

(10, 3)
It means it has 10 rows and 3 columns


4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [9]:
arrayRow = int(input("Please enter row number: "))
arrayCol = int(input("Please enter column number: "))

numArray = np.ones((arrayRow, arrayCol))

for i in range(arrayRow):
    for j in range(arrayCol):
        if (i +  1) % 2 == 0 and (j + 1) % 2 == 0:
            numArray[i][j] = 0

print(numArray)


Please enter row number:  6
Please enter column number:  5


[[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]]
